### PR TITLE
Mt stretch api

### PR DESCRIPTION
**Pull request by bortami**
refactored build itinerary function

need to call a function call to save.js to call cloneToNode(spanName, i)

### CODE REVIEW

**Comment by bortami** [comment]
now has button to save current itinerary!

**Comment by bortami** [comment]
finally, it now does as described. the save current button has an event listener which calls a PUT request, splits a string, trims annoying invisible trailing spaces so  /n         /n no longer shows up in the json.  changes to index.html and resultsbuilder.js was to remove spaces

you should be able to search any field, save it from the results to the itinerary field, and then save the completed itinerary to object 1 of the json database. 
it will rewrite object 1 of json everytime you click the "save current itin" button.

**Comment by bortami** [comment]
don't forget you have to be running the json server ....grunt in the library.

**Comment by sydneywait** [comment]
🐔

**Comment by Downeastrussell** [comment]
looks good so far! 🥇

**Comment by sydneywait** [comment]
🍨

**Pull request merged**
